var Sequelize = require('sequelize');
var sequelize = new Sequelize('codeoil', 'codeoil', '');

module.exports = (function() {
    return {
        Attempt: sequelize.define('attempt', {
            attempt: Sequelize.BIGINT, // generated by the backend, returned from the frontend
            hash: Sequelize.STRING, // hash generated by aggregators
            generated: Sequelize.BOOLEAN, // true if the record was generated by backend
            resolution: Sequelize.ENUM('UNRESOLVED', 'RESOLVED_CORRECT', 'RESOLVED_INCORRECT'), // only ever resolved when !generated
            resolvedAt: Sequelize.DATE, // datetime, when the resolution was reached
        }), 
    };
})();