var Sequelize = require('sequelize');
var sequelize = new Sequelize('codeoil', 'codeoil', '');

module.exports = (function() {
    var models = {
        Attempt: sequelize.define('attempt', {
            attempt: Sequelize.BIGINT,          // generated by the backend, returned from the frontend
            hash: Sequelize.STRING,             // hash generated by aggregators
            correct: Sequelize.BOOLEAN,         // true if it matched a solution
            attemptSeq: Sequelize.INTEGER,      // the sequence number of this attempt among all attempts for this attempt ID (delayed)
            questionSeq: Sequelize.INTEGER,     // the sequence number of this attempt among all attempts for this question ID (delayed)
        }), 
        Solution: sequelize.define('solution', {
            attempt: Sequelize.BIGINT,
            hash: Sequelize.STRING,
        }),
    };
    
    // Add a key connecting the solution to the model that first solved it
    models.Solution.belongsTo(models.Attempt, {as: 'SolvedBy'})
    
    return models;
})();